### ISSUE TITLE
LimitExceeded

### ISSUE THREAD

**Issue by sufnoobzac** [hitrov/oci-arm-host-capacity#35]
I don't have any instances running, but got this error (LimitExceeded). why?

![err](https://user-images.githubusercontent.com/15175579/168001622-2eb636f6-3862-4e08-8be7-406e453de1f6.jpg)

**Comment by hitrov** [comment]
check her
<img width="1338" alt="Screenshot 2022-05-12 at 09 10 57" src="https://user-images.githubusercontent.com/26094610/168003588-798bc0d1-1aea-4b97-81ad-d9091680b94f.png">
<img width="1340" alt="Screenshot 2022-05-12 at 09 09 17" src="https://user-images.githubusercontent.com/26094610/168003596-1ca1e05b-4843-40cc-879f-8792613cb626.png">
e

**Comment by Rtchyc** [comment]
Can I launch an instance? as?

**Comment by avephill** [comment]
I'm confused because I am also consistently receiving the error `The following service limits were exceeded: standard-a1-memory-count, standard-a1-memory-regional-count, standard-a1-core-count, standard-a1-core-regional-count.` but I see the following when I look at my limits: 

![2022-12-14_3185x924](https://user-images.githubusercontent.com/56899195/207745276-8a628725-0735-4332-8f73-9a682a92bb21.png)

I must have made a mistake in parameterizing the instance?

**Comment by hitrov** [comment]
make sure to set availability domain the same as on screenshot. also try to create an instance from the UI in the browser - to check whether you'll get the same error as from the API response. other than that, i'd suggest to reach Oracle support
